// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {worlds} from '../models';
import {mods} from '../models';
import {updater} from '../models';
import {config} from '../models';
import {skin} from '../models';
import {app} from '../models';
import {news} from '../models';

export function BackupWorld(arg1:string):Promise<worlds.World>;

export function CheckModUpdates():Promise<Array<mods.Mod>>;

export function CheckUpdate():Promise<updater.Asset>;

export function DeleteBackup(arg1:string):Promise<void>;

export function DeleteGame():Promise<void>;

export function DeleteWorld(arg1:string):Promise<void>;

export function DownloadAndLaunch(arg1:string):Promise<void>;

export function DownloadVersion(arg1:string,arg2:string):Promise<void>;

export function ExitGame():Promise<void>;

export function GetAvailableColors():Promise<Array<string>>;

export function GetAvailableVersions():Promise<Record<string, number>>;

export function GetBackups():Promise<Array<worlds.World>>;

export function GetConfig():Promise<config.Config>;

export function GetCosmeticCategories():Promise<Record<string, Array<skin.CosmeticItem>>>;

export function GetCrashReports():Promise<Array<app.CrashReport>>;

export function GetCurrentVersion():Promise<string>;

export function GetGameLogs():Promise<string>;

export function GetGamePath():Promise<string>;

export function GetInstalledMods():Promise<Array<mods.Mod>>;

export function GetInstalledVersions():Promise<Array<app.InstalledVersion>>;

export function GetLauncherVersion():Promise<string>;

export function GetLogs():Promise<string>;

export function GetModCategories():Promise<Array<mods.ModCategory>>;

export function GetMusicEnabled():Promise<boolean>;

export function GetNews(arg1:number):Promise<Array<news.NewsItem>>;

export function GetNick():Promise<string>;

export function GetPlatformInfo():Promise<Record<string, string>>;

export function GetSkinPreset():Promise<skin.AvatarPreset>;

export function GetVersions():Promise<string|string>;

export function GetWorld(arg1:string):Promise<worlds.World>;

export function GetWorlds():Promise<Array<worlds.World>>;

export function InstallMod(arg1:number):Promise<void>;

export function IsGameInstalled():Promise<boolean>;

export function IsGameRunning():Promise<boolean>;

export function OpenFolder():Promise<void>;

export function OpenGameFolder():Promise<void>;

export function OpenModsFolder():Promise<void>;

export function OpenWorldsFolder():Promise<void>;

export function QuickLaunch():Promise<void>;

export function RenameWorld(arg1:string,arg2:string):Promise<void>;

export function RepairInstallation():Promise<void>;

export function RestoreBackup(arg1:string):Promise<worlds.World>;

export function RunDiagnostics():Promise<app.DiagnosticReport>;

export function SaveConfig():Promise<void>;

export function SaveDiagnosticReport():Promise<string>;

export function SaveSkinPreset(arg1:skin.AvatarPreset):Promise<void>;

export function SearchMods(arg1:string,arg2:number,arg3:number):Promise<mods.SearchResult>;

export function SetMusicEnabled(arg1:boolean):Promise<void>;

export function SetNick(arg1:string):Promise<void>;

export function SwitchVersion(arg1:number):Promise<void>;

export function ToggleMod(arg1:string,arg2:boolean):Promise<void>;

export function UninstallMod(arg1:string):Promise<void>;

export function Update():Promise<void>;
