// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BackupWorld(arg1) {
  return window['go']['app']['App']['BackupWorld'](arg1);
}

export function CheckModUpdates() {
  return window['go']['app']['App']['CheckModUpdates']();
}

export function CheckUpdate() {
  return window['go']['app']['App']['CheckUpdate']();
}

export function DeleteBackup(arg1) {
  return window['go']['app']['App']['DeleteBackup'](arg1);
}

export function DeleteGame() {
  return window['go']['app']['App']['DeleteGame']();
}

export function DeleteWorld(arg1) {
  return window['go']['app']['App']['DeleteWorld'](arg1);
}

export function DownloadAndLaunch(arg1) {
  return window['go']['app']['App']['DownloadAndLaunch'](arg1);
}

export function DownloadVersion(arg1, arg2) {
  return window['go']['app']['App']['DownloadVersion'](arg1, arg2);
}

export function ExitGame() {
  return window['go']['app']['App']['ExitGame']();
}

export function GetAvailableColors() {
  return window['go']['app']['App']['GetAvailableColors']();
}

export function GetAvailableVersions() {
  return window['go']['app']['App']['GetAvailableVersions']();
}

export function GetBackups() {
  return window['go']['app']['App']['GetBackups']();
}

export function GetConfig() {
  return window['go']['app']['App']['GetConfig']();
}

export function GetCosmeticCategories() {
  return window['go']['app']['App']['GetCosmeticCategories']();
}

export function GetCrashReports() {
  return window['go']['app']['App']['GetCrashReports']();
}

export function GetCurrentVersion() {
  return window['go']['app']['App']['GetCurrentVersion']();
}

export function GetGameLogs() {
  return window['go']['app']['App']['GetGameLogs']();
}

export function GetGamePath() {
  return window['go']['app']['App']['GetGamePath']();
}

export function GetInstalledMods() {
  return window['go']['app']['App']['GetInstalledMods']();
}

export function GetInstalledVersions() {
  return window['go']['app']['App']['GetInstalledVersions']();
}

export function GetLauncherVersion() {
  return window['go']['app']['App']['GetLauncherVersion']();
}

export function GetLogs() {
  return window['go']['app']['App']['GetLogs']();
}

export function GetModCategories() {
  return window['go']['app']['App']['GetModCategories']();
}

export function GetMusicEnabled() {
  return window['go']['app']['App']['GetMusicEnabled']();
}

export function GetNews(arg1) {
  return window['go']['app']['App']['GetNews'](arg1);
}

export function GetNick() {
  return window['go']['app']['App']['GetNick']();
}

export function GetPlatformInfo() {
  return window['go']['app']['App']['GetPlatformInfo']();
}

export function GetSkinPreset() {
  return window['go']['app']['App']['GetSkinPreset']();
}

export function GetVersions() {
  return window['go']['app']['App']['GetVersions']();
}

export function GetWorld(arg1) {
  return window['go']['app']['App']['GetWorld'](arg1);
}

export function GetWorlds() {
  return window['go']['app']['App']['GetWorlds']();
}

export function InstallMod(arg1) {
  return window['go']['app']['App']['InstallMod'](arg1);
}

export function IsGameInstalled() {
  return window['go']['app']['App']['IsGameInstalled']();
}

export function IsGameRunning() {
  return window['go']['app']['App']['IsGameRunning']();
}

export function OpenFolder() {
  return window['go']['app']['App']['OpenFolder']();
}

export function OpenGameFolder() {
  return window['go']['app']['App']['OpenGameFolder']();
}

export function OpenModsFolder() {
  return window['go']['app']['App']['OpenModsFolder']();
}

export function OpenWorldsFolder() {
  return window['go']['app']['App']['OpenWorldsFolder']();
}

export function QuickLaunch() {
  return window['go']['app']['App']['QuickLaunch']();
}

export function RenameWorld(arg1, arg2) {
  return window['go']['app']['App']['RenameWorld'](arg1, arg2);
}

export function RepairInstallation() {
  return window['go']['app']['App']['RepairInstallation']();
}

export function RestoreBackup(arg1) {
  return window['go']['app']['App']['RestoreBackup'](arg1);
}

export function RunDiagnostics() {
  return window['go']['app']['App']['RunDiagnostics']();
}

export function SaveConfig() {
  return window['go']['app']['App']['SaveConfig']();
}

export function SaveDiagnosticReport() {
  return window['go']['app']['App']['SaveDiagnosticReport']();
}

export function SaveSkinPreset(arg1) {
  return window['go']['app']['App']['SaveSkinPreset'](arg1);
}

export function SearchMods(arg1, arg2, arg3) {
  return window['go']['app']['App']['SearchMods'](arg1, arg2, arg3);
}

export function SetMusicEnabled(arg1) {
  return window['go']['app']['App']['SetMusicEnabled'](arg1);
}

export function SetNick(arg1) {
  return window['go']['app']['App']['SetNick'](arg1);
}

export function SwitchVersion(arg1) {
  return window['go']['app']['App']['SwitchVersion'](arg1);
}

export function ToggleMod(arg1, arg2) {
  return window['go']['app']['App']['ToggleMod'](arg1, arg2);
}

export function UninstallMod(arg1) {
  return window['go']['app']['App']['UninstallMod'](arg1);
}

export function Update() {
  return window['go']['app']['App']['Update']();
}
