/*
 .-..-.      .---.       _                  
 : :; :      : .; :     :_;                 
 :    :.-..-.:  _.'.--. .-. .--. ,-.,-.,-.  
 : :: :: :; :: :   : ..': :`._-.': ,. ,. : 
 :_;:_;`._. ;:_;   :_;  :_;`.__.':_;:_;:_;
        .-. :                               
        `._.'            generated IPC API 

AUTO-GENERATED BY generate-ipc.mjs — DO NOT EDIT MANUALLY!
SOURCE: Services/Core/IpcService.cs (@type + @ipc annotations)
*/

// eslint-disable-next-line @typescript-eslint/no-require-imports
const { ipcRenderer } = (window as any).require('electron');

// #region Core IPC helpers

export function send(channel: string, data?: unknown): void {
  ipcRenderer.send(channel, data != null ? JSON.stringify(data) : undefined);
}

export function on(channel: string, callback: (data: unknown) => void): () => void {
  const listener = (_event: unknown, ...args: unknown[]) => {
    const raw = args.length === 1 ? args[0] : args;
    // Backend sends JSON.Serialize(data), so we need to parse it
    let parsed = raw;
    if (typeof raw === 'string') {
      try { parsed = JSON.parse(raw); } catch { /* keep raw */ }
    }
    callback(parsed);
  };
  ipcRenderer.on(channel, listener);
  return () => { ipcRenderer.removeListener(channel, listener); };
}

export function invoke<T = unknown>(channel: string, data?: unknown, timeout = 10000): Promise<T> {
  return new Promise((resolve, reject) => {
    const replyChannel = `${channel}:reply`;
    const timer = setTimeout(() => {
      cleanup();
      reject(new Error(`IPC timeout on ${channel}`));
    }, timeout);

    const cleanup = on(replyChannel, (response) => {
      clearTimeout(timer);
      cleanup();
      try {
        const parsed = typeof response === 'string' ? JSON.parse(response) : response;
        resolve(parsed as T);
      } catch {
        resolve(response as T);
      }
    });

    send(channel, data);
  });
}

// #endregion

// #region Types (from @type annotations)

export interface ProgressUpdate {
  state: string;
  progress: number;
  messageKey: string;
  args?: unknown[];
  downloadedBytes: number;
  totalBytes: number;
}

export interface GameState {
  state: 'starting' | 'started' | 'running' | 'stopped';
  exitCode: number;
}

export interface GameError {
  type: string;
  message: string;
  technical?: string;
}

export interface NewsItem {
  title: string;
  excerpt?: string;
  url?: string;
  date?: string;
  publishedAt?: string;
  author?: string;
  imageUrl?: string;
  source?: string;
}

export interface Profile {
  id: string;
  name: string;
  uuid?: string;
  isOfficial?: boolean;
  avatar?: string;
  folderName?: string;
}

export interface HytaleAuthStatus {
  loggedIn: boolean;
  username?: string;
  uuid?: string;
  error?: string;
  errorType?: string;
}

export interface ProfileSnapshot {
  nick: string;
  uuid: string;
  avatarPath?: string;
}

export interface SettingsSnapshot {
  language: string;
  musicEnabled: boolean;
  launcherBranch: string;
  closeAfterLaunch: boolean;
  showDiscordAnnouncements: boolean;
  disableNews: boolean;
  backgroundMode: string;
  availableBackgrounds: string[];
  accentColor: string;
  hasCompletedOnboarding: boolean;
  onlineMode: boolean;
  authDomain: string;
  dataDirectory: string;
  gpuPreference?: string;
  launchOnStartup?: boolean;
  minimizeToTray?: boolean;
  animations?: boolean;
  transparency?: boolean;
  resolution?: string;
  ramMb?: number;
  sound?: boolean;
  closeOnLaunch?: boolean;
  developerMode?: boolean;
  verboseLogging?: boolean;
  preRelease?: boolean;
  [key: string]: unknown;
}

export interface ModItem {
  id: string;
  name: string;
  description?: string;
  version?: string;
  author?: string;
  iconUrl?: string;
  isInstalled: boolean;
  featured?: boolean;
  downloads?: number;
}

export interface ModSearchResult {
  items: ModItem[];
  totalCount: number;
}

export interface AppConfig {
  language: string;
  dataDirectory: string;
  [key: string]: unknown;
}

export interface InstalledInstance {
  branch: string;
  version: number;
  path: string;
  hasUserData: boolean;
  userDataSize: number;
  totalSize: number;
  isValid: boolean;
}

export interface LanguageInfo {
  code: string;
  name: string;
}

export interface GpuAdapterInfo {
  name: string;
  vendor: string;
  type: string;
}

export interface SaveInfo {
  name: string;
  path: string;
  sizeBytes?: number;
  lastModified?: string;
  previewPath?: string;
}

// #endregion

// #region Typed IPC API (from @ipc annotations)

const _config = {
  get: () => invoke<AppConfig>('hyprism:config:get'),
  save: (data?: unknown) => invoke<{ success: boolean }>('hyprism:config:save', data),
};

const _game = {
  launch: (data?: { branch?: string; version?: number }) => send('hyprism:game:launch', data),
  cancel: () => send('hyprism:game:cancel'),
  instances: () => invoke<InstalledInstance[]>('hyprism:game:instances'),
  isRunning: (data?: unknown) => invoke<boolean>('hyprism:game:isRunning', data),
  versions: (data?: unknown) => invoke<number[]>('hyprism:game:versions', data),
  onProgress: (cb: (data: ProgressUpdate) => void) => on('hyprism:game:progress', cb as (d: unknown) => void),
  onState: (cb: (data: GameState) => void) => on('hyprism:game:state', cb as (d: unknown) => void),
  onError: (cb: (data: GameError) => void) => on('hyprism:game:error', cb as (d: unknown) => void),
};

const _instance = {
  delete: (data?: unknown) => invoke<boolean>('hyprism:instance:delete', data),
  openFolder: () => send('hyprism:instance:openFolder'),
  openModsFolder: () => send('hyprism:instance:openModsFolder'),
  export: (data?: unknown) => invoke<string>('hyprism:instance:export', data),
  import: (data?: unknown) => invoke<boolean>('hyprism:instance:import', data),
  saves: (data?: unknown) => invoke<SaveInfo[]>('hyprism:instance:saves', data),
  openSaveFolder: () => send('hyprism:instance:openSaveFolder'),
  getIcon: (data?: unknown) => invoke<string | null>('hyprism:instance:getIcon', data),
};

const _news = {
  get: () => invoke<NewsItem[]>('hyprism:news:get'),
};

const _profile = {
  get: () => invoke<ProfileSnapshot>('hyprism:profile:get'),
  list: () => invoke<Profile[]>('hyprism:profile:list'),
  switch: (data?: unknown) => invoke<{ success: boolean }>('hyprism:profile:switch', data),
  setNick: (data?: unknown) => invoke<{ success: boolean }>('hyprism:profile:setNick', data),
  setUuid: (data?: unknown) => invoke<{ success: boolean }>('hyprism:profile:setUuid', data),
  create: (data?: unknown) => invoke<Profile>('hyprism:profile:create', data),
  delete: (data?: unknown) => invoke<{ success: boolean }>('hyprism:profile:delete', data),
  activeIndex: (data?: unknown) => invoke<number>('hyprism:profile:activeIndex', data),
  save: (data?: unknown) => invoke<{ success: boolean }>('hyprism:profile:save', data),
  duplicate: (data?: unknown) => invoke<Profile>('hyprism:profile:duplicate', data),
  openFolder: () => send('hyprism:profile:openFolder'),
  avatarForUuid: (data?: unknown) => invoke<string>('hyprism:profile:avatarForUuid', data),
};

const _auth = {
  status: (data?: unknown) => invoke<HytaleAuthStatus>('hyprism:auth:status', data),
  login: (data?: unknown) => invoke<HytaleAuthStatus>('hyprism:auth:login', data),
  logout: (data?: unknown) => invoke<{ success: boolean }>('hyprism:auth:logout', data),
};

const _settings = {
  get: () => invoke<SettingsSnapshot>('hyprism:settings:get'),
  update: (data?: unknown) => invoke<{ success: boolean }>('hyprism:settings:update', data),
  launcherPath: (data?: unknown) => invoke<string>('hyprism:settings:launcherPath', data),
  defaultInstanceDir: (data?: unknown) => invoke<string>('hyprism:settings:defaultInstanceDir', data),
  setInstanceDir: (path: string) => invoke<void>('hyprism:settings:setInstanceDir', { path }),
  setLauncherDataDir: (path: string) => invoke<void>('hyprism:settings:setLauncherDataDir', { path }),
};

const _i18n = {
  get: () => invoke<Record<string, string>>('hyprism:i18n:get'),
  current: () => invoke<string>('hyprism:i18n:current'),
  set: (data?: unknown) => invoke<{ success: boolean, language: string }>('hyprism:i18n:set', data),
  languages: () => invoke<LanguageInfo[]>('hyprism:i18n:languages'),
};

const _window = {
  minimize: () => send('hyprism:window:minimize'),
  maximize: () => send('hyprism:window:maximize'),
  close: () => send('hyprism:window:close'),
};

const _browser = {
  open: (data: string) => send('hyprism:browser:open', data),
};

const _mods = {
  list: () => invoke<ModItem[]>('hyprism:mods:list'),
  search: (data?: unknown) => invoke<ModSearchResult>('hyprism:mods:search', data),
  installed: (data?: unknown) => invoke<ModItem[]>('hyprism:mods:installed', data),
  uninstall: (data?: unknown) => invoke<boolean>('hyprism:mods:uninstall', data),
  checkUpdates: (data?: unknown) => invoke<ModItem[]>('hyprism:mods:checkUpdates', data),
};

const _system = {
  gpuAdapters: () => invoke<GpuAdapterInfo[]>('hyprism:system:gpuAdapters'),
};

const _console = {
  log: (msg: string) => send('hyprism:console:log', msg),
  warn: (msg: string) => send('hyprism:console:warn', msg),
  error: (msg: string) => send('hyprism:console:error', msg),
};

const _file = {
  browseFolder: (data?: unknown) => invoke<string | null>('hyprism:file:browseFolder', data),
};

// #endregion

// #region Unified export

export const ipc = {
  config: _config,
  game: _game,
  instance: _instance,
  news: _news,
  profile: _profile,
  auth: _auth,
  settings: _settings,
  i18n: _i18n,
  windowCtl: _window,
  browser: _browser,
  mods: _mods,
  system: _system,
  consoleCtl: _console,
  file: _file,
};

// #endregion
